// src/constants/dropdownOptions.js
export const dropdownOptions = [
    { value: "B/A Servs", label: "B/A Servs" },
    { value: "Counseling", label: "Counseling" },
    { value: "Court", label: "Court" },
    { value: "Dental Appt", label: "Dental Appt" },
    { value: "DFCS Off D/O", label: "DFCS Off D/O" },
    { value: "DFCS Off P/U", label: "DFCS Off P/U" },
    { value: "Drug Scrn", label: "Drug Scrn" },
    { value: "Fam/Rel Visit", label: "Fam/Rel Visit" },
    { value: "FH Visit", label: "FH Visit" },
    { value: "From Drug Screen", label: "From Drug Screen" },
    { value: "FTM Mtg", label: "FTM Mtg" },
    { value: "Hosp. Supv", label: "Hosp. Supv" },
    { value: "Hotel Supervision", label: "Hotel Supervision" },
    { value: "Hotel Supv D/O", label: "Hotel Supv D/O" },
    { value: "Hotel Supv P/U", label: "Hotel Supv P/U" },
    { value: "IHCM Servs", label: "IHCM Servs" },
    { value: "Meal", label: "Meal" },
    { value: "Med Appt.", label: "Med Appt." },
    { value: "Med Appt. 2", label: "Med Appt. 2" },
    { value: "Med Appt. 3", label: "Med Appt. 3" },
    { value: "MT Mtg", label: "MT Mtg" },
    { value: "New Placemt D/O", label: "New Placemt D/O" },
    { value: "New Placemt P/U", label: "New Placemt P/U" },
    { value: "Parent Aide Svs", label: "Parent Aide Svs" },
    { value: "Placement D/O", label: "Placement D/O" },
    { value: "Placement D/O 2", label: "Placement D/O 2" },
    { value: "Placement P/U", label: "Placement P/U" },
    { value: "Placement P/U 2", label: "Placement P/U 2" },
    { value: "Return Home/Office/closest location", label: "Return Home/Office/closest location" },
    { value: "School D/O", label: "School D/O" },
    { value: "School D/O 2", label: "School D/O 2" },
    { value: "School P/U", label: "School P/U" },
    { value: "School P/U 2", label: "School P/U 2" },
    { value: "Supervised visit", label: "Supervised visit" },
    { value: "Therapy Appt", label: "Therapy Appt" },
    { value: "To Drug Screen", label: "To Drug Screen" },
    { value: "Unsupervised visit", label: "Unsupervised visit" },
    { value: "Work P/U", label: "Work P/U" },
  ];
  